const SelectableCountries = () => [
    'Afganistán',
    'Albania',
    'Alemania',
    'Andorra',
    'Angola',
    'Antigua y Barbuda',
    'Arabia Saudita',
    'Argelia',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaiyán',
    'Bahamas',
    'Bangladés',
    'Barbados',
    'Baréin',
    'Bélgica',
    'Belice',
    'Benín',
    'Bielorrusia',
    'Birmania',
    'Bolivia',
    'Bosnia y Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunéi',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Bután',
    'Cabo Verde',
    'Camboya',
    'Camerún',
    'Canadá',
    'Catar',
    'Chad',
    'Chile',
    'China',
    'Chipre',
    'Ciudad del Vaticano',
    'Colombia',
    'Comoras',
    'Corea del Norte',
    'Corea del Sur',
    'Costa de Marfil',
    'Costa Rica',
    'Croacia',
    'Cuba',
    'Dinamarca',
    'Dominica',
    'Ecuador',
    'Egipto',
    'El Salvador',
    'Emiratos Árabes Unidos',
    'Eritrea',
    'Eslovaquia',
    'Eslovenia',
    'España',
    'Estados Unidos',
    'Estonia',
    'Etiopía',
    'Filipinas',
    'Finlandia',
    'Fiyi',
    'Francia',
    'Gabón',
    'Gambia',
    'Georgia',
    'Ghana',
    'Granada',
    'Grecia',
    'Guatemala',
    'Guyana',
    'Guinea',
    'Guinea ecuatorial',
    'Guinea-Bisáu',
    'Haití',
    'Honduras',
    'Hungría',
    'India',
    'Indonesia',
    'Irak',
    'Irán',
    'Irlanda',
    'Islandia',
    'Islas Marshall',
    'Islas Salomón',
    'Israel',
    'Italia',
    'Jamaica',
    'Japón',
    'Jordania',
    'Kazajistán',
    'Kenia',
    'Kirguistán',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letonia',
    'Líbano',
    'Liberia',
    'Libia',
    'Liechtenstein',
    'Lituania',
    'Luxemburgo',
    'Macedonia del Norte',
    'Madagascar',
    'Malasia',
    'Malaui',
    'Maldivas',
    'Malí',
    'Malta',
    'Marruecos',
    'Mauricio',
    'Mauritania',
    'México',
    'Micronesia',
    'Moldavia',
    'Mónaco',
    'Mongolia',
    'Montenegro',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Níger',
    'Nigeria',
    'Noruega',
    'Nueva Zelanda',
    'Omán',
    'Países Bajos',
    'Pakistán',
    'Palaos',
    'Panamá',
    'Papúa Nueva Guinea',
    'Paraguay',
    'Perú',
    'Polonia',
    'Portugal',
    'Reino Unido',
    'República Centroafricana',
    'República Checa',
    'República del Congo',
    'República Democrática del Congo',
    'República Dominicana',
    'Ruanda',
    'Rumanía',
    'Rusia',
    'Samoa',
    'San Cristóbal y Nieves',
    'San Marino',
    'San Vicente y las Granadinas',
    'Santa Lucía',
    'Santo Tomé y Príncipe',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leona',
    'Singapur',
    'Siria',
    'Somalia',
    'Sri Lanka',
    'Suazilandia',
    'Sudáfrica',
    'Sudán',
    'Sudán del Sur',
    'Suecia',
    'Suiza',
    'Surinam',
    'Tailandia',
    'Tanzania',
    'Tayikistán',
    'Timor Oriental',
    'Togo',
    'Tonga',
    'Trinidad y Tobago',
    'Túnez',
    'Turkmenistán',
    'Turquía',
    'Tuvalu',
    'Ucrania',
    'Uganda',
    'Uruguay',
    'Uzbekistán',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Yibuti',
    'Zambia',
    'Zimbabue',
];

// [
// 'AFGANISTAN',
// 'ALBANIA',
// 'ALEMANIA',
// 'ANDORRA',
// 'ANGOLA',
// 'ANGUILLA',
// 'ANTIGUA Y BARBUDA',
// 'ANTILLAS HOLANDESAS',
// 'ARABIA SAUDI',
// 'ARGELIA',
// 'ARGENTINA',
// 'ARMENIA',
// 'ARUBA',
// 'AUSTRALIA',
// 'AUSTRIA',
// 'AZERBAIYAN',
// 'BAHAMAS',
// 'BAHREIN',
// 'BANGLADESH',
// 'BARBADOS',
// 'BELARUS',
// 'BELGICA',
// 'BELICE',
// 'BENIN',
// 'BERMUDAS',
// 'BHUTÁN',
// 'BOLIVIA',
// 'BOSNIA Y HERZEGOVINA',
// 'BOTSWANA',
// 'BRASIL',
// 'BRUNEI',
// 'BULGARIA',
// 'BURKINA FASO',
// 'BURUNDI',
// 'CABO VERDE',
// 'CAMBOYA',
// 'CAMERUN',
// 'CANADA',
// 'CHAD',
// 'CHILE',
// 'CHINA',
// 'CHIPRE',
// 'COLOMBIA',
// 'COMORES',
// 'CONGO',
// 'COREA',
// 'COREA DEL NORTE',
// 'COSTA DE MARFIL',
// 'COSTA RICA',
// 'CROACIA',
// 'CUBA',
// 'DINAMARCA',
// 'DJIBOUTI',
// 'DOMINICA',
// 'ECUADOR',
// 'EGIPTO',
// 'EL SALVADOR',
// 'EMIRATOS ARABES UNIDOS',
// 'ERITREA',
// 'ESLOVENIA',
// 'ESPAÑA',
// 'ESTADOS UNIDOS DE AMERICA',
// 'ESTONIA',
// 'ETIOPIA',
// 'FIJI',
// 'FILIPINAS',
// 'FINLANDIA',
// 'FRANCIA',
// 'GABON',
// 'GAMBIA',
// 'GEORGIA',
// 'GHANA',
// 'GIBRALTAR',
// 'GRANADA',
// 'GRECIA',
// 'GROENLANDIA',
// 'GUADALUPE',
// 'GUAM',
// 'GUATEMALA',
// 'GUAYANA FRANCESA',
// 'GUERNESEY',
// 'GUINEA',
// 'GUINEA ECUATORIAL',
// 'GUINEA-BISSAU',
// 'GUYANA',
// 'HAITI',
// 'HONDURAS',
// 'HONG KONG',
// 'HUNGRIA',
// 'INDIA',
// 'INDONESIA',
// 'IRAN',
// 'IRAQ',
// 'IRLANDA',
// 'ISLA DE MAN',
// 'ISLA NORFOLK',
// 'ISLANDIA',
// 'ISLAS ALAND',
// 'ISLAS CAIMÁN',
// 'ISLAS COOK',
// 'ISLAS DEL CANAL',
// 'ISLAS FEROE',
// 'ISLAS MALVINAS',
// 'ISLAS MARIANAS DEL NORTE',
// 'ISLAS MARSHALL',
// 'ISLAS PITCAIRN',
// 'ISLAS SALOMON',
// 'ISLAS TURCAS Y CAICOS',
// 'ISLAS VIRGENES BRITANICAS',
// 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
// 'ISRAEL',
// 'ITALIA',
// 'JAMAICA',
// 'JAPON',
// 'JERSEY',
// 'JORDANIA',
// 'KAZAJSTAN',
// 'KENIA',
// 'KIRGUISTAN',
// 'KIRIBATI',
// 'KUWAIT',
// 'LAOS',
// 'LESOTHO',
// 'LETONIA',
// 'LIBANO',
// 'LIBERIA',
// 'LIBIA',
// 'LIECHTENSTEIN',
// 'LITUANIA',
// 'LUXEMBURGO',
// 'MACAO',
// 'MACEDONIA',
// 'MADAGASCAR',
// 'MALASIA',
// 'MALAWI',
// 'MALDIVAS',
// 'MALI',
// 'MALTA',
// 'MARRUECOS',
// 'MARTINICA',
// 'MAURICIO',
// 'MAURITANIA',
// 'MAYOTTE',
// 'MEXICO',
// 'MICRONESIA',
// 'MOLDAVIA',
// 'MONACO',
// 'MONGOLIA',
// 'MONTENEGRO',
// 'MONTSERRAT',
// 'MOZAMBIQUE',
// 'MYANMAR',
// 'NAMIBIA',
// 'NAURU',
// 'NEPAL',
// 'NICARAGUA',
// 'NIGER',
// 'NIGERIA',
// 'NIUE',
// 'NORUEGA',
// 'NUEVA CALEDONIA',
// 'NUEVA ZELANDA',
// 'OMAN',
// 'PAISES BAJOS',
// 'PAKISTAN',
// 'PALAOS',
// 'PALESTINA',
// 'PANAMA',
// 'PAPUA NUEVA GUINEA',
// 'PARAGUAY',
// 'PERU',
// 'POLINESIA FRANCESA',
// 'POLONIA',
// 'PORTUGAL',
// 'PUERTO RICO',
// 'QATAR',
// 'REINO UNIDO',
// 'REP.DEMOCRATICA DEL CONGO',
// 'REPUBLICA CENTROAFRICANA',
// 'REPUBLICA CHECA',
// 'REPUBLICA DOMINICANA',
// 'REPUBLICA ESLOVACA',
// 'REUNION',
// 'RUANDA',
// 'RUMANIA',
// 'RUSIA',
// 'SAHARA OCCIDENTAL',
// 'SAMOA',
// 'SAMOA AMERICANA',
// 'SAN BARTOLOME',
// 'SAN CRISTOBAL Y NIEVES',
// 'SAN MARINO',
// 'SAN MARTIN (PARTE FRANCESA)',
// 'SAN PEDRO Y MIQUELON',
// 'SAN VICENTE Y LAS GRANADINAS',
// 'SANTA HELENA',
// 'SANTA LUCIA',
// 'SANTA SEDE',
// 'SANTO TOME Y PRINCIPE',
// 'SENEGAL',
// 'SERBIA',
// 'SEYCHELLES',
// 'SIERRA LEONA',
// 'SINGAPUR',
// 'SIRIA',
// 'SOMALIA',
// 'SRI LANKA',
// 'SUDAFRICA',
// 'SUDAN',
// 'SUECIA',
// 'SUIZA',
// 'SURINAM',
// 'SVALBARD Y JAN MAYEN',
// 'SWAZILANDIA',
// 'TADYIKISTAN',
// 'TAILANDIA',
// 'TANZANIA',
// 'TIMOR ORIENTAL',
// 'TOGO',
// 'TOKELAU',
// 'TONGA',
// 'TRINIDAD Y TOBAGO',
// 'TUNEZ',
// 'TURKMENISTAN',
// 'TURQUIA',
// 'TUVALU',
// 'UCRANIA',
// 'UGANDA',
// 'URUGUAY',
// 'UZBEKISTAN',
// 'VANUATU',
// 'VENEZUELA',
// 'VIETNAM',
// 'WALLIS Y FORTUNA',
// 'YEMEN',
// 'ZAMBIA',
// 'ZIMBABWE',
// ]

const compareArrays = (array1, array2) => {
    let arr = [];
    array1.forEach(value=>{
        let found = array2.find(element => {
            return element.toLowerCase() === str.toLowerCase();
          });
        if(!array2.includes(value))
            arr.push({v: value, desc:`${value} not included in second array`})
    })
    array2.forEach(value=>{
        if(!array1.includes(value))
            arr.push({v: value, desc:`${value} not included in first array`})
    })

    return arr
}

export {
    SelectableCountries
}