const SelectableOccupations = () => [
    'Agricultores y trabajadores calificados de explotaciones agropecuarias con destino al mercado',
    'Artesanos y operarios de las artes gráficas',
    'Ayudantes de preparación de alimentos',
    'Conductores de vehiculos y operadores de equipos pesados móviles',
    'Directores administradores y comerciales',
    'Directores ejecutivos, personal directivo de la administración pública y miembros del poder ejecutivo y de cuerpos legislativos ',
    'Directores y gerentes de producción y operaciones',
    'Ejerce profesión (casos en que aplica)',
    'Empleados contables y encargados del registro de materiales',
    'Empleados en trato directo con el público',
    'Ensambladores',
    'Estudiantes',
    'Gerentes de hoteles, resturantes, comercios, y otros',
    'Investigadores y consultores Limpiadores y asistentes',
    'Limpiadores y asistentes',
    'No aplica',
    'Oficiales y operarios de la construcción (excluyendo electricistas) ',
    'Oficiales y operarios de la metalurgia, la construcción mecanica, y afines',
    'Oficinistas',
    'Operadores de instalaciones fijas y máquinas',
    'Operarios y oficiales de procesamiento de alimentos, de la confección, ebanistas, otros artesanos, y afines',
    'Otro personal de apoyo administrativo',
    'Peones agropecuarios, pesqueros, y forestales',
    'Peones de la minería, la construcción, la industria manufacturera, y el transporte',
    'Personal de los servicios de protección',
    'Personal militar',
    'Recolectores de desechos y otras ocupaciones elementales',
    'Retiradas y jubiladas pensionadas',
    'Trabajadora sexual',
    'Trabajadoras domésticas no asalariadas',
    'Trabajadores agropecuarios, pescadores, cazadores, y recolectores de subsistencia Trabajadores de los cuidados personales',
    'Trabajadores de los cuidados personales',
    'Trabajadores de los servicios personales',
    'Trabajadores especializados en electricidad y la electrotecnologia ',
    'Trabajadores forestales calificados, pescadores, y cazadores',
    'Vendedores',
    'Vendedores ambulantes de servicios y afines',
    'Otro'
];

export {
    SelectableOccupations
}